server:
  port: 8084

spring:
  application:
    name: notification-service

  kafka:
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

notification:
  topic:
    payment: payment-events
