server:
  port: 8084

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
    topic:
      payment: payment-events

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
