server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: Nive2303

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

payment:
  topic: payment-events
  
jwt:
  secret: paymentServiceSuperSecretKey_32chars_min_123456
  expiration: 3600000
