server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: Nive2303

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: userServiceSecretKey_32chars_min_123456
  expiration: 3600000
